import {
  AccountChangesNotification,
  MessageNotification,
  AccountRequestNotification,
  DocumentNotification,
  SystemNotification,
  JobOrderNotification,
} from "./Objects.js";

export const notifications = [
  new AccountChangesNotification({
    id: 1,
    title: "Account Updated",
    message: "Your profile information was updated.",
    updatedFields: [
      { name: "Email", value: "sample@gmail.com" },
      { name: "Contact Number", value: "123490283" },
    ],
    updatedBy: 1,
    timestamp: new Date("2025-11-22T10:30:00"),
    isRead: true,
  }),
  new MessageNotification({
    id: 2,
    title: "New Message",
    message: "John sent you a message.",
    conversationId: 1,
    timestamp: new Date("2025-11-22T12:00:00"),
  }),
  new AccountRequestNotification({
    id: 3,
    title: "New Account Request",
    message: "A new account is awaiting approval.",
    requestId: 1,
    userId: 2,
    status: "pending",
    timestamp: new Date("2025-11-21T09:15:00"),
    isRead: true,
  }),
  new DocumentNotification({
    id: 4,
    title: "Document Approved",
    message: "Invoice #9982 has been approved.",
    documentId: 2,
    userId: 5,
    action: "approved",
    timestamp: new Date("2025-11-20T14:45:00"),
  }),
  new SystemNotification({
    id: 5,
    title: "System Maintenance",
    message: "The system will be offline tonight from 10 PM to 12 AM.",
    severity: "high",
    affectedServices: [
      "User Registration",
      "Document uploads",
      "Payment processing",
    ],
    timestamp: new Date("2025-11-22T08:00:00"),
  }),
  new JobOrderNotification({
    id: 6,
    title: "New Job Order",
    message: "Job Order #1 was assigned to you.",
    jobId: 1,
    updatedBy: 5,
    status: "updated",
    isRead: true,
    timestamp: new Date("2025-11-22T13:20:00"),
  }),
  new JobOrderNotification({
    id: 7,
    title: "New Job Order",
    message: "Job Order #2 was assigned to you.",
    jobId: 1,
    updatedBy: 2,
    status: "updated",
    timestamp: new Date("2025-11-22T13:20:00"),
  }),
];
